require conf/distro/poky.conf

DISTRO = "beaglebone-distro"
DISTRO_NAME = "BeagleBone Black Distribution"
DISTRO_VERSION = "1.0"

# Enable systemd and required features
DISTRO_FEATURES:append = " systemd usrmerge"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"

# Use systemd as init system
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

# Enable Rust in this specific version
DISTRO_FEATURES:append = " rust"
RUST_VERSION = "1.85.1"
CARGO_VERSION = "1.85.1"


UBOOT_EXTLINUX = "1"

UBOOT_EXTLINUX_FDTOVERLAYS = "/overlays/testoverlay.dtbo"


IMAGE_BOOT_FILES += "overlays/*.dtbo;overlays/"
IMAGE_BOOT_FILES += "extlinux.conf;extlinux/"
